services:
  - type: web
    name: techexam
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: "20.x"
      - key: DATABASE_URL
        sync: false
      - key: JWT_STUDENT_SECRET
        sync: false
      - key: JWT_ADMIN_SECRET
        sync: false
      - key: ADMIN_USERNAME
        value: ADMIN
      - key: ADMIN_PASSWORD
        value: ADMIN123